# Generated by Django 2.2 on 2019-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190508_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='content',
            field=models.CharField(default=-1.0, max_length=300),
            preserve_default=False,
        ),
    ]
