# Generated by Django 2.2 on 2019-05-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_upload_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='content',
        ),
        migrations.AddField(
            model_name='upload',
            name='body',
            field=models.TextField(default=-1.0, max_length=300),
            preserve_default=False,
        ),
    ]
